# Generated by Django 3.2.9 on 2021-12-07 10:05

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_subadmin', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('assistance', models.BooleanField(default=False, verbose_name='Have You Recieved Assistance from us before')),
                ('theAssistance', models.TextField(verbose_name='Kindly Give information About the Assistance')),
                ('similar', models.BooleanField(default=False, verbose_name='Have You Recieved Similar Assistance from else where')),
                ('theSimilar', models.TextField(verbose_name='Kindly Give details of the Assistance')),
                ('since', models.DateField(verbose_name='Since When')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistance',
                'verbose_name_plural': 'Assistances',
            },
        ),
        migrations.CreateModel(
            name='EmployentDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('status', models.BooleanField(default=False, verbose_name='Are you Current Employed')),
                ('company', models.CharField(max_length=150)),
                ('since', models.DateField(verbose_name='Since When')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EmployentDetails',
                'verbose_name_plural': 'EmployentDetailss',
            },
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('marital', models.CharField(choices=[('1', 'Married'), ('2', 'Divorced'), ('3', 'Widowed')], max_length=1, verbose_name='What is Your Marital Status')),
                ('spouse', models.CharField(max_length=50, verbose_name='Spouse Name')),
                ('spouse_employment', models.BooleanField(verbose_name='Does Your Spouse Employeed')),
                ('employee_address', models.CharField(max_length=250, verbose_name='Spouse Employee Address')),
                ('phone', models.PositiveBigIntegerField(verbose_name='Spouse PhoneNumber')),
                ('job', models.CharField(max_length=50, verbose_name='Job Title')),
                ('kids', models.PositiveBigIntegerField(verbose_name='No of Children')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FamilyDetails',
                'verbose_name_plural': 'FamilyDetailss',
            },
        ),
        migrations.CreateModel(
            name='NeedDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('needs', models.TextField(verbose_name='Eplain The Extract Nature of Your Need')),
                ('status', models.CharField(choices=[('1', 'SUBMITTED'), ('2', 'UNDER-PROCESS'), ('3', 'APPROVED'), ('4', 'COMPLETED')], default='SUBMITTED', max_length=1)),
                ('when_complete', models.DateField()),
                ('value', models.TextField(blank=True, verbose_name='What given to The Needy')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NeedDatails',
                'verbose_name_plural': 'NeedDatailss',
            },
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('place_of_birth', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('1', 'ABIA'), ('2', 'ADAMAWA')], default='ABIA', max_length=1)),
                ('education', models.CharField(choices=[('1', 'PRIMARY SCHOOL'), ('2', 'SCHOOL LEAVING CERTICATE')], default='SCHOOL LEAVING CERTICATE', max_length=1)),
                ('religion', models.CharField(choices=[('1', 'ISLAM'), ('2', 'CHRISTAINITY')], default='ISLAM', max_length=1)),
                ('attend', models.CharField(blank=True, max_length=250, null=True, verbose_name='Which Masjeed or Church do You Attend')),
                ('phone_number', models.PositiveIntegerField()),
                ('passport', models.ImageField(upload_to='needy', verbose_name='Passport Photography')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PersonalDetails',
                'verbose_name_plural': 'PersonalDetailss',
            },
        ),
        migrations.CreateModel(
            name='RefereesDetails',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.PositiveBigIntegerField()),
                ('relationship', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RefereesDetails',
                'verbose_name_plural': 'RefereesDetailss',
            },
        ),
        migrations.CreateModel(
            name='SkilsDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('skill', models.BooleanField(default=False, verbose_name='Are you Skilled')),
                ('skill_details', models.TextField(verbose_name='More Details About Your Skill')),
                ('vocation', models.BooleanField(default=False, verbose_name='Do You Have any Vocational Traning')),
                ('vocational_details', models.TextField(verbose_name='More Details About Your Vocation Course')),
                ('vocation_info', models.TextField(verbose_name='More Info About Who train You and the Address')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SkilsDetails',
                'verbose_name_plural': 'SkilsDetailss',
            },
        ),
        migrations.CreateModel(
            name='SubAdminProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('place_of_birth', models.CharField(max_length=150)),
                ('phone_number', models.PositiveIntegerField()),
                ('passport', models.ImageField(upload_to='subadmin', verbose_name='Passport Photography')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SubAdminProfile',
                'verbose_name_plural': 'SubAdminProfiles',
            },
        ),
    ]
